runtime: nodejs20
service: frontend  # <--- This is the key part that saperates frontend from backend service.

handlers:
  - url: /
    static_files: dist/index.html
    upload: dist/index.html

  - url: /(.*)
    static_files: dist/\1
    upload: dist/(.*)