runtime: nodejs20

env_variables:
  DB_HOST: 34.121.169.193   # Your Cloud SQL public IP
  DB_USER: root
  DB_PASS: Talganize@124
  DB_NAME: talganize
  INSTANCE_CONNECTION_NAME: talganize-dev:us-central1:talganizedb

automatic_scaling:
  min_instances: 1
  max_instances: 3
